from enum import IntEnum


class FAHMessage(IntEnum):
    MSG_ID_NEW_SESSION = 1
    PROTOCOL_VERSION = 1
    AUTH_TYPE_USER = 0
    MSG_ID_LOGIN_SASL = 12
    MSG_ID_NEW_SESSION_RESULT = 2
    MSG_ID_CRYPTED_CONTAINER_TO_CLIENT = 65
    MSG_ID_ERROR_RESPONSE = 100
    MSG_ID_CRYPTED_CONTAINER_TO_SERVER = 64
    MSG_ID_RPC_CALL_RESULT = 6
    MSG_ID_SASL_CHALLENGE = 13
    MSG_ID_SASL_LOGIN_SUCCESS = 15
    MSG_ID_SASL_RESPONSE = 14
    MSG_ID_RPC_CALL = 5


class Result(IntEnum):
    RESULT_CODE_OK = 0


class General(IntEnum):
    PROTOCOL_VERSION = 1
    FH_CRYPTO_MAC_LENGTH = 16
